# Generated by Django 4.2.3 on 2023-07-09 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='precio',
            field=models.IntegerField(default=-2024),
            preserve_default=False,
        ),
    ]
