# Generated by Django 4.2.3 on 2023-07-09 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_vehiculos_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehiculos',
            new_name='Vehiculo',
        ),
    ]
