# Generated by Django 4.2.3 on 2023-07-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_rename_vehiculos_vehiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='serial_carroceria',
            new_name='carroceria',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='serial_motor',
            new_name='motor',
        ),
    ]
